import { Product } from "./data.interface";

const products: Product[] = [
  {
    name: "Eren Yeager",
    slug: "eren-yeager",
    category: "Attack on Titan",
    image: "/images/products/eren.png",
    price: 15,
    brand: "POP!",
    rating: 4.5,
    numReviews: 5,
    countInStock: 10,
    description: "Product Description Goes Here",
  },
  {
    name: "Zeke Yeager",
    slug: "zeke-yaeger",
    category: "Attack on Titan",
    image: "/images/products/zeke.png",
    price: 15,
    brand: "POP!",
    rating: 4.5,
    numReviews: 5,
    countInStock: 10,
    description: "Product Description Goes Here",
  },
  {
    name: "Mikasa Ackerman",
    slug: "mikasa-ackerman",
    category: "Attack on Titan",
    image: "/images/products/mikasa.png",
    price: 15,
    brand: "POP!",
    rating: 4.5,
    numReviews: 5,
    countInStock: 10,
    description: "Product Description Goes Here",
  },
  {
    name: "Attack Titan",
    slug: "eren-yaegar-iced",
    category: "Attack on Titan",
    image: "/images/products/eren_ice.png",
    price: 15,
    brand: "POP!",
    rating: 4.5,
    numReviews: 5,
    countInStock: 10,
    description: "Product Description Goes Here",
  },
  {
    name: "Naruto Uzamaki",
    slug: "naruto-uzamaki",
    category: "Naruto Shippuden",
    image: "/images/products/naruto.png",
    price: 15,
    brand: "POP!",
    rating: 4.5,
    numReviews: 5,
    countInStock: 10,
    description: "Product Description Goes Here",
  },
  {
    name: "Kurama",
    slug: "kurama",
    category: "Naruto Shippuden",
    image: "/images/products/kurama.png",
    price: 15,
    brand: "POP!",
    rating: 4.5,
    numReviews: 5,
    countInStock: 10,
    description: "Product Description Goes Here",
  },
  {
    name: "Kakashi Hatake",
    slug: "kakashi-hatake",
    category: "Naruto Shippuden",
    image: "/images/products/kakashi.png",
    price: 15,
    brand: "POP!",
    rating: 4.5,
    numReviews: 5,
    countInStock: 10,
    description: "Product Description Goes Here",
  },
  {
    name: "Madara Uchiha",
    slug: "madara-uchiha",
    category: "Naruto Shippuden",
    image: "/images/products/madara.png",
    price: 15,
    brand: "POP!",
    rating: 4.5,
    numReviews: 5,
    countInStock: 10,
    description: "Product Description Goes Here",
  },
  {
    name: "Tobi",
    slug: "tobi",
    category: "Naruto Shippuden",
    image: "/images/products/tobi.png",
    price: 15,
    brand: "POP!",
    rating: 4.5,
    numReviews: 5,
    countInStock: 10,
    description: "Product Description Goes Here",
  },
  {
    name: "Luffy (Snake-Man)",
    slug: "luffy-snake-man",
    category: "One Piece",
    image: "/images/products/luffy.png",
    price: 15,
    brand: "POP!",
    rating: 4.5,
    numReviews: 5,
    countInStock: 10,
    description: "Product Description Goes Here",
  },
  {
    name: "Roronoa Zoro",
    slug: "roronoa-zoro",
    category: "One Piece",
    image: "/images/products/zoro.png",
    price: 15,
    brand: "POP!",
    rating: 4.5,
    numReviews: 5,
    countInStock: 10,
    description: "Product Description Goes Here",
  },
  {
    name: "Eustass Kidd",
    slug: "eustass-kidd",
    category: "One Piece",
    image: "/images/products/eustass.png",
    price: 15,
    brand: "POP!",
    rating: 4.5,
    numReviews: 5,
    countInStock: 10,
    description: "Product Description Goes Here",
  },
  {
    name: "Trafalgar Law",
    slug: "trafalgar-law",
    category: "One Piece",
    image: "/images/products/law.png",
    price: 15,
    brand: "POP!",
    rating: 4.5,
    numReviews: 5,
    countInStock: 10,
    description: "Product Description Goes Here",
  },

  {
    name: "Lebron James",
    slug: "lebron-james",
    category: "NBA",
    image: "/images/products/lebron.png",
    price: 15,
    brand: "POP!",
    rating: 4.5,
    numReviews: 5,
    countInStock: 10,
    description: "Product Description Goes Here",
  },
  {
    name: "Michael Jordan",
    slug: "michael-jordan",
    category: "NBA",
    image: "/images/products/jordan.png",
    price: 15,
    brand: "POP!",
    rating: 4.5,
    numReviews: 5,
    countInStock: 10,
    description: "Product Description Goes Here",
  },
  {
    name: "Tanjiro Vs. Rui",
    slug: "tanjiro-vs-rui",
    category: "Demon Slayer",
    image: "/images/products/tanjiro2.png",
    price: 50,
    brand: "POP! Moments",
    rating: 4.5,
    numReviews: 5,
    countInStock: 10,
    description: "Product Description Goes Here",
  },
  {
    name: "Timon & Pumbaa",
    slug: "timon-pumbaa",
    category: "Disney",
    image: "/images/products/lionking.png",
    price: 50,
    brand: "POP! Moments",
    rating: 4.5,
    numReviews: 5,
    countInStock: 10,
    description: "Product Description Goes Here",
  },
];

export default products;
