import { Product } from "./data.interface";

const products: Product[] = [
  {
    name: "Sora",
    slug: "sora",
    category: "KH",
    image: "/images/sora.png",
    price: 15,
    brand: "funko",
    rating: 4.5,
    numReviews: 5,
    countInStock: 10,
    description: "Lorem ipsum dolor sit amet",
  },
  {
    name: "Sora2",
    slug: "sora2",
    category: "KH",
    image: "/images/sora.png",
    price: 15,
    brand: "funko",
    rating: 4.5,
    numReviews: 5,
    countInStock: 10,
    description: "Lorem ipsum dolor sit amet",
  },
  {
    name: "Sor3a",
    slug: "sora3",
    category: "KH",
    image: "/images/sora.png",
    price: 15,
    brand: "funko",
    rating: 4.5,
    numReviews: 5,
    countInStock: 10,
    description: "Lorem ipsum dolor sit amet",
  },
  {
    name: "Sor4a",
    slug: "sora4",
    category: "KH",
    image: "/images/sora.png",
    price: 15,
    brand: "funko",
    rating: 4.5,
    numReviews: 5,
    countInStock: 10,
    description: "Lorem ipsum dolor sit amet",
  },
  {
    name: "Naruto",
    slug: "naruto",
    category: "shonen",
    image: "/images/naruto.png",
    price: 15,
    brand: "funko",
    rating: 4.5,
    numReviews: 5,
    countInStock: 10,
    description: "Lorem ipsum dolor sit amet",
  },
  {
    name: "Itachi",
    slug: "itachi",
    category: "shonen",
    image: "/images/itachi.png",
    price: 15,
    brand: "funko",
    rating: 4.5,
    numReviews: 5,
    countInStock: 10,
    description: "Lorem ipsum dolor sit amet",
  },
  {
    name: "Axel",
    slug: "axel",
    category: "KH",
    image: "/images/axel.png",
    price: 15,
    brand: "funko",
    rating: 4.5,
    numReviews: 5,
    countInStock: 10,
    description: "Lorem ipsum dolor sit amet",
  },
  {
    name: "Broly",
    slug: "broly",
    category: "shonen",
    image: "/images/broly.png",
    price: 15,
    brand: "funko",
    rating: 4.5,
    numReviews: 5,
    countInStock: 10,
    description: "Lorem ipsum dolor sit amet",
  },
  {
    name: "Goku",
    slug: "goku",
    category: "shonen",
    image: "/images/goku.png",
    price: 15,
    brand: "funko",
    rating: 4.5,
    numReviews: 5,
    countInStock: 10,
    description: "Lorem ipsum dolor sit amet",
  },
];

export default products;
